before_install:
  - gem update bundler rake
branches:
  only:
    - master
    - v4
env:
  global:
    - secure: | # CODECLIMATE_REPO_TOKEN
        BIemhM273wHZMpuULDMYGPsxYdfw+NMw7IQbOD6gy5r+dha07y9ssTYYE5Gn
        t1ptAb09lhQ4gexXTr83i6angMrnHgQ1ZX2wfeoZ0FvWDHQht9YkXyiNH+R6
        odHUeDIYAlUiqLX9nAkklL89Rc22BrHMGGNyuA8Uc5sktW5P/FE=
language: ruby
matrix:
  allow_failures:
    - rvm: ruby-head
notifications:
  webhooks:
    on_start: always
    urls:
      - http://buildlight.collectiveidea.com/
rvm:
  - "2.0"
  - "2.1"
  - "2.2"
  - "2.3.3"
  - "2.4.0"
  - ruby-head
script: bundle exec rspec
